# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main, master, dev, dev-environment, prod-test, test-environment ]
  pull_request:
    branches: [ main, master, dev, dev-environment, prod-test, test-environment ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        # Gradle version to use
        gradle-version: 6.3
        # Path to the root directory of the build
        build-root-directory: .
        # Whether caching wrapper installation is enabled or not, default to 'true'
        wrapper-cache-enabled: true
        # Whether caching dependencies is enabled or not, default to 'false'
        dependencies-cache-enabled: true
        # Gradle command line arguments, see gradle --help
        arguments: build
